### PR TITLE
Added Savi packaging of LatLongToTimeZone. (TEMPORARY PR for name questions (and PR test).)

### PR DESCRIPTION
**Pull request by dsbos**
@jamescnowell

### CODE REVIEW

**Comment by jamescnowell** [comment]
So I did some digging with this thing. I couldn't get the C code to build on Linux or OSX. There are `vcproj` files checked in and hard coded Windows paths on Dr. Tim's computer, even if I could get it to build.

I looked at the output JSON and spent about 15 minutes reproducing the JSON with Java and Geotools. No C code needed. Still a little hacky, but it could be polished up. 

Moving on to the next phase, the Java code that generates the output files is also really really really rough. There's some elements of the JSON.org Java reference implementation copied into this repo. It looks like the implementation of the k-d tree might be the only thing worth keeping, but JTS (Java Topology Suite) has an implementation of R Tree optimized for spatial indexing. 

I think we should probably use the codegen Java file for now, but it would be a good idea to go ahead and make a real java equivalent to tz_where.

**Comment by jamescnowell** [comment]
Oh, also tz_world doesn't have oceanic timezone data, even coastal waters. And apparently ship captains can change their clock any time after entering an international waters timezone, with midnight being the most common time to change. So this will only work for land based shipments.

**Comment by dsbos** [comment]
> make a real java equivalent to tz_where.

Note that we already have a Savi clone (well, GitHub fork) of tzwhere-java.

**Comment by jamescnowell** [comment]
I checked out tzwhere-java; it's using the right tools, but is implemented without an index (like the original tzwhere), so it will be much slower. I'd still go with this over that, I think. 

I'll have to look at JTS's tree code and see how it compares. It might just be worth contributing back to this repo.

**Pull request closed without merging**
